
language: node_js

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never

node_js:
  - 10.0.0

branches:
  only:
    - master

before_install: git fetch --depth=100

install:
  - npm i

script:
  - commitlint-travis
  - npm run build
  - npm test

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
