
language: node_js

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never

node_js:
  - 8.6.0

branches:
  only:
    - master

before_install: git fetch --depth=100

install:
  - npm i
  - npm run build

script:
  - /bin/bash build/lint-commits.sh

after_success:
  - npm run cover:hook
