
language: node_js

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never

node_js:
  - 10.0.0

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn build
  - yarn test

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
